she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index')
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

she_codes_news/news/models.py
from django.db import models


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    content = models.TextField()

she_codes_news/news/views.py
from django.views import generic
from .models import NewsStory


class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all()[:4]
        return context

she_codes_news/news/templates/news/index.html
    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                <p>{{ story.title }}</p>
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                <p>{{ story.title }}</p>
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

she_codes_news/news/templates/news/story.html
<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">
        <img src="{% static '/news/images/placeholder-5.jpg' %}">
        {{ story.content|linebreaks }}
    </div>
</div>

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="">
        {% if position < 5 %}
            <img src="../static/news/images/placeholder-{{ position }}.jpg">
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Hayley van Waas">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="">
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            <!-- include nav here -->
        </header>

        <!-- content blocks here -->
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    <a href="#">username</a>
    <a href="#">Logout</a>
    <a href="#">Login</a>
</nav>